// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dortpsqvcjvmbhntnowo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcnRwc3F2Y2p2bWJobnRub3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTE2OTksImV4cCI6MjA2ODY4NzY5OX0.HK-GsVokxMKd5osHeCa-22l3Ot7P3rP7KZzfcRSQHEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});